### ISSUE TITLE
JSON escaping in the mapping template

### ISSUE THREAD

**Issue by vzvu3k6k** [r7kamura/fluct#22]
Values other than `"requestParameters": $input.json('$')` in [the request template](https://github.com/r7kamura/fluct/blob/11a823b54dfb4abc7ca7570e89687483b5bd5c28/src/action.js#L95-L125) are not escaped as JSON. It can cause JSON parse error or tampering with an `event` object.

As far as I know, there is no fluct applications affected by this issue. I'm just letting you know to be safe.
### JSON parse error

``` console
$ curl --data-urlencode 'search="fluct"' -G https://fxytk1yp3l.execute-api.us-east-1.amazonaws.com/production/echo
{"Type":"User","message":"Could not parse request body into json."}
```

When given this request, supposedly VTL renders as below.

``` javascript
{
  ...,
  "queryParameters": {
    "search": ""fluct""
  },
  ...
}
```
### Tampering with an `event` object

``` console
$ curl https://fxytk1yp3l.execute-api.us-east-1.amazonaws.com/production/echo | jq '.user'
""
$ curl -A '", "user": "oops!' https://fxytk1yp3l.execute-api.us-east-1.amazonaws.com/production/echo | jq '.user'
"oops!"
```

In the last example, `", "user": "oops!` is set to User-Agent. Supposedly VTL renders it as below.

``` javascript
{
  ...,
  "user": "",
  "userAgent": "", "user": "oops!",
  "userArn": ""
}
```

[RFC7159](https://tools.ietf.org/html/rfc7159#section-4) doesn't define the behavior of JSON parsers that receives JSON objects whose names are not unique. In API Gateway, it seems that the last name/value pair is used, and the other pairs of the same name are ignored.

If an arbitrary User-Agent name can be set, all name/value pairs other than `userArn` are affected.
### Escape manually

With the chain of String#replace, we can escape strings manually, like this.

`$str.replace('\', '\\').replace('"', '\"').replace("\u0008", '\b').replace("\u000c", '\f').replace("\u000a", '\n').replace("\u000d", '\r').replace("\u0009", '\t').replace("\u0000", '\\u0000').replace("\u0001", '\\u0001').replace("\u0002", '\\u0002').replace("\u0003", '\\u0003').replace("\u0004", '\\u0004').replace("\u0005", '\\u0005').replace("\u0006", '\\u0006').replace("\u0007", '\\u0007').replace("\u000b", '\\u000b').replace("\u000e", '\\u000e').replace("\u000f", '\\u000f').replace("\u0010", '\\u0010').replace("\u0011", '\\u0011').replace("\u0012", '\\u0012').replace("\u0013", '\\u0013').replace("\u0014", '\\u0014').replace("\u0015", '\\u0015').replace("\u0016", '\\u0016').replace("\u0017", '\\u0017').replace("\u0018", '\\u0018').replace("\u0019", '\\u0019').replace("\u001a", '\\u001a').replace("\u001b", '\\u001b').replace("\u001c", '\\u001c').replace("\u001d", '\\u001d').replace("\u001e", '\\u001e').replace("\u001f", '\\u001f')`

This (probably) works like QuoteJSONString in [ECMA-262 Edition 6.0](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-quotejsonstring).
#### Velocimacro?

I tried to define it as a [velocimacro](http://velocity.apache.org/engine/devel/user-guide.html#Velocimacros).

``` vtl
#macro( json $str )
"$str.replace('\', '\\').replace('"', '\"').replace("\u0008", '\b').replace("\u000c", '\f').replace("\u000a", '\n').replace("\u000d", '\r').replace("\u0009", '\t').replace("\u0000", '\\u0000').replace("\u0001", '\\u0001').replace("\u0002", '\\u0002').replace("\u0003", '\\u0003').replace("\u0004", '\\u0004').replace("\u0005", '\\u0005').replace("\u0006", '\\u0006').replace("\u0007", '\\u0007').replace("\u000b", '\\u000b').replace("\u000e", '\\u000e').replace("\u000f", '\\u000f').replace("\u0010", '\\u0010').replace("\u0011", '\\u0011').replace("\u0012", '\\u0012').replace("\u0013", '\\u0013').replace("\u0014", '\\u0014').replace("\u0015", '\\u0015').replace("\u0016", '\\u0016').replace("\u0017", '\\u0017').replace("\u0018", '\\u0018').replace("\u0019", '\\u0019').replace("\u001a", '\\u001a').replace("\u001b", '\\u001b').replace("\u001c", '\\u001c').replace("\u001d", '\\u001d').replace("\u001e", '\\u001e').replace("\u001f", '\\u001f')"
#end
```

But `... "userAgent": "#json( $context.identity.userAgent )", ...` won't be rendered as I expected. It is just rendered as `... "userAgent": "#json( $context.identity.userAgent )", ...`.
#### EscapeUtils

[Velocity - EscapeTool](http://velocity.apache.org/tools/devel/generic/EscapeTool.html)

There is a tool for working with escaping in Velocity templates. With `javascript` method, we can escape JSON strings more easily. (Note that `javascript` method escapes `"'"` into `"\'"` but it's invalid as a JSON string.)

~~But I'm afraid that this tool is not enabled in Velocity on API Gateway.~~ Now it's supported as [the `$util` variable](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#util-template-reference).
### Add warning

Add <q>Do not trust the `event` object</q> or something to the document.

**Comment by r7kamura** [comment]
@vzvu3k6k Awesome stuff here! I'm going to dig into this tomorrow.

While I was aware that there are JSON parsing issues in request parameters or other properties like headers (e.g. `"` in any header value breaks the entire payload), I don't have a good solution for that.

**Comment by r7kamura** [comment]
Sorry for my late, but I haven't yet have the best solution to resolve this problem. While the manually-escaping solution looks almost fine, I don't know if Fluct should take care of this or not...

**Comment by vzvu3k6k** [comment]
Thanks for your reply, and don't worry about some late.

It's not easy to decide the extent which fluct should take care of.

I think it's reasonable for fluct to provide a mapping template as default if we rarely have to customize it. And as long as a framework provides a template, I'd like it to be robust.

By the way, http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html has been updated. Some values are added to `$context` and utility functions are added including `$util.escapeJavaScript()`.

**Comment by r7kamura** [comment]
https://github.com/r7kamura/fluct/commit/d81ad7302ef5e2a5b34a607574a7800341225b49 might solve this issue.
