### ISSUE TITLE
Add support for different regions

### ISSUE THREAD

**Issue by AxelTheGerman** [r7kamura/fluct#30]
AWS region is hard coded to `us-east-1`. Lambda and DynamoDB support other regions, such as `us-west-2`.
Allow the developer to set the region for deployment, either through `~/.aws/config` (get's generates by `aws configure`) or fluct parameter in top-level `package.json`

https://github.com/r7kamura/fluct/search?q=us-east-1

**Comment by r7kamura** [comment]
Thanks @axelgustav!  I agree with you that we should make it able to specify the region in package.json. I'm going to support that in the future, but I'm currently using only `us-east-1` region in my projects. If anyone sends a pull request, I'm willing to merge it :pray:
