### ISSUE TITLE
can't run example deploy command

### ISSUE THREAD

**Issue by tjmcewan** [r7kamura/fluct#39]
Following the readme example exactly, I get:

```
$ fluct deploy
Created zip: ./actions/list_users/lambda.zip
Uploaded function: list_users
Created restapi: 7yxmn7t994
TypeError: body._embedded.item.map is not a function
    at /usr/local/lib/node_modules/amazon-api-gateway-client/lib/client.js:303:36
    at process._tickDomainCallback (node.js:420:9)
```

I'm new-ish to node/lambda, so I'm not sure what debugging info I should provide to help narrow down where the problem could be.

Notable though, if I create the Resource manually (and only the Resource, no Methods), it then proceeds without any problems.  It's repeatable.

**Comment by tjmcewan** [comment]
Further to this, I've just deployed your example app.  It failed with the same error the first time, so I created just one of the Resources.  It worked fine after that, creating the rest with no troubles. :)

**Comment by jtwebman** [comment]
I am getting this same error. Though it looks like it might be an aws error as _emdedded is an object not an array anymore.

**Comment by jtwebman** [comment]
Actually looks like it is another issue. I added a pull request to amazon-api-gateway-client (https://github.com/r7kamura/amazon-api-gateway-client/pull/8) to make it better at error handling. I'll send a pull request here as well to fix the issue and handle the errors better.

**Comment by okmttdhr** [comment]
> It failed with the same error the first time, so I created just one of the Resources.

I solved the problem with this.

**Comment by aycabta** [comment]
> I added a pull request to amazon-api-gateway-client (r7kamura/amazon-api-gateway-client#8) to make it better at error handling.

I think https://github.com/fluct/fluct/pull/38 solved this problem. Please try to use Fluct 0.4.0, @jtwebman and @tjmcewan. The latest version of Fluct doesn't use `amazon-api-gateway-client`.

**Comment by jtwebman** [comment]
Awesome yes the aws-sdk has the gateway now.
