### ISSUE TITLE
Warn about incompatibility with Node v0.10.36 (Lambda's supported version)

### ISSUE THREAD

**Issue by taromero** [r7kamura/fluct#44]
Running `fluct deploy` while using Node v.0.10.36 results in:

```
/home/tomas/.nvm/v0.10.36/lib/node_modules/fluct/lib/composer.js:210
      return Promise.all(this.application.getActions().map(function (action) {
             ^
ReferenceError: Promise is not defined
    at Composer.createZipFiles (/home/tomas/.nvm/v0.10.36/lib/node_modules/fluct/lib/composer.js:210:14)
```

I changed to using v.0.12.0 and it worked.

As 0.10.36 is the [version of Node that Lambda runs](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html), I think many developers will be running that version locally and could face this problem. Thus, I think this should be either corrected (so that it doesn't rely on 0.10.36 unsopported ES6 features) or warned in the readme.

**Comment by aycabta** [comment]
I resolved on #45.
