### ISSUE TITLE
Wrong build on npm

### ISSUE THREAD

**Issue by MiniGod** [r7kamura/fluct#47]
I just installed fluct with  
`npm install fluct -g`

When I try to run it, I get
`Error: Cannot find module 'amazon-api-gateway-client'`

After further investigation, it looks like the `lib` directory has the contents of `v0.3.x`, since `amazon-api-gateway-client` was removed in `v0.4.0`.

Could you build it and re-publish?

**Comment by okmttdhr** [comment]
+1

(I got the same error with `v0.4.0`. So I'm using `v0.3.x`...)

**Comment by MiniGod** [comment]
Looks like `v0.4.1` was published just 29 hours after this issue was created.

I can confirm that it works. Thanks @r7kamura
